import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar/Navbar";
import ShopcartContextprovider from "./components/Context/ShopcartContext";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "my shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShopcartContextprovider>
          <Navbar />
          {children}
          <Footer/>
        </ShopcartContextprovider>
      </body>
    </html>
  );
}
